/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,ts,jsx,tsx}", "./index.html"],
  theme: {
    extend: {
      colors: {
        // DESIGN.md color tokens
        primary: "#181d26",
        "primary-active": "#0d1218",
        ink: "#181d26",
        body: "#333840",
        muted: "#41454d",
        hairline: "#dddddd",
        "border-strong": "#9297a0",
        canvas: "#ffffff",
        "surface-soft": "#f8fafc",
        "surface-strong": "#e0e2e6",
        "surface-dark": "#181d26",
        "surface-dark-elevated": "#1d1f25",
        "on-primary": "#ffffff",
        "on-dark": "#ffffff",
        link: "#1b61c9",
        "link-active": "#1a3866",
        info: "#254fad",
        "info-border": "#458fff",
        success: "#006400",
        "success-border": "#39bf45",
        "pricing-ink": "#1d1f25",
        // Signature colors
        "signature-coral": "#aa2d00",
        "signature-forest": "#0a2e0e",
        "signature-cream": "#f5e9d4",
        "signature-peach": "#fcab79",
        "signature-mint": "#a8d8c4",
        "signature-yellow": "#f4d35e",
        "signature-mustard": "#d9a441",
        // Legacy compatibility (maps to DESIGN.md tokens)
        "border-gray": "#dddddd",
      },
      borderRadius: {
        xs: "2px",
        sm: "6px",
        md: "10px",
        lg: "12px",
        pill: "9999px",
        full: "9999px",
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        section: "96px",
      },
      fontSize: {
        "display-xl": ["48px", { lineHeight: "1.1", fontWeight: "500" }],
        "display-lg": ["40px", { lineHeight: "1.2", fontWeight: "400" }],
        "display-md": ["32px", { lineHeight: "1.2", fontWeight: "400" }],
        "title-lg": ["24px", { lineHeight: "1.35", fontWeight: "400", letterSpacing: "0.12px" }],
        "title-md": ["20px", { lineHeight: "1.5", fontWeight: "400" }],
        "title-sm": ["18px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-md": ["16px", { lineHeight: "1.4", fontWeight: "500" }],
        caption: ["14px", { lineHeight: "1.35", fontWeight: "500", letterSpacing: "0.16px" }],
        legal: ["13.12px", { lineHeight: "1.2", fontWeight: "600" }],
        button: ["16px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "1.25", fontWeight: "400" }],
      },
      fontFamily: {
        display: [
          "Inter Display",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          "Oxygen",
          "Ubuntu",
          "Cantarell",
          '"Fira Sans"',
          '"Droid Sans"',
          '"Helvetica Neue"',
          "sans-serif",
        ],
        body: [
          "Inter",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          "Oxygen",
          "Ubuntu",
          "Cantarell",
          '"Fira Sans"',
          '"Droid Sans"',
          '"Helvetica Neue"',
          "sans-serif",
        ],
        mono: [
          "JetBrains Mono",
          "Fira Code",
          "Source Code Pro",
          "Consolas",
          "Monaco",
          "Menlo",
          "Ubuntu Mono",
          "DejaVu Sans Mono",
          "monospace",
        ],
        code: [
          "JetBrains Mono",
          "Fira Code",
          "Source Code Pro",
          "Consolas",
          "Monaco",
          "Menlo",
          "Ubuntu Mono",
          "DejaVu Sans Mono",
          "monospace",
        ],
      },
      boxShadow: {
        button: "0 2px 0 rgba(27, 97, 201, 0.02)",
        "button-focus": "0 0 0 2px rgba(69, 143, 255, 0.35)",
      },
    },
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "2rem",
        lg: "4rem",
        xl: "5rem",
        "2xl": "6rem",
      },
    },
  },
  darkMode: "class",
  plugins: [],
};
